### ISSUE TITLE
ansible_doc_generator/doc_generator.rb:59:in `join': no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by augustync** [PopulateTools/ansible-doc-generator#19]
```
❯ ansible-doc-generator -p roles.yml
/usr/local/lib/ruby/gems/3.0.0/gems/ansible_doc_generator-0.1.0/lib/ansible_doc_generator/doc_generator.rb:59:in `join': no implicit conversion of nil into String (TypeError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/ansible_doc_generator-0.1.0/lib/ansible_doc_generator/doc_generator.rb:59:in `tasks_yml_path_for_role'
	from /usr/local/lib/ruby/gems/3.0.0/gems/ansible_doc_generator-0.1.0/lib/ansible_doc_generator/doc_generator.rb:26:in `block in parse_roles'
	from /usr/local/lib/ruby/gems/3.0.0/gems/ansible_doc_generator-0.1.0/lib/ansible_doc_generator/doc_generator.rb:25:in `each'
	from /usr/local/lib/ruby/gems/3.0.0/gems/ansible_doc_generator-0.1.0/lib/ansible_doc_generator/doc_generator.rb:25:in `parse_roles'
	from /usr/local/lib/ruby/gems/3.0.0/gems/ansible_doc_generator-0.1.0/lib/ansible_doc_generator/doc_generator.rb:18:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/ansible_doc_generator-0.1.0/bin/ansible-doc-generator:39:in `<top (required)>'
	from /usr/local/bin/ansible-doc-generator:23:in `load'
	from /usr/local/bin/ansible-doc-generator:23:in `<main>'
```

Any idea why this is happening 

gem installed:
- ansible_doc_generator (0.1.0)

```
❯  gem --version
3.2.15
❯  ruby --version
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin20]
```

**Comment by ferblape** [comment]
Hi @augustync I think it's because of using Ruby 3. We've tested only with Ruby 2.7.x. We'll take a look ASAP

**Comment by eltercero** [comment]
Hi, @augustync 

Thanks a lot for reporting this.

I think this might be due to have some roles without the `role` key with the path. Meaning, in the yml there should be something like:

```yaml
  roles:
    - { role: 'handlers' }
    - { role: 'chores/centos/install_base_packages' }
```

Because the gem iterates through all the roles to add the documentation for each one. 

I updated the code to fix this bug and it will ignore those roles without the path. Could you please try the new version? Since the gem is not updated yet, you'll need to install the source code and run it from there like:

```
git clone https://github.com/PopulateTools/ansible-doc-generator.git
cd ansible-doc-generator
bin/setup
bin/ansible-doc-generator -p /path/to/your/roles.yml
```

Please let us know if this fixed it. If not, could you please attach a non-working `roles.yml` example so we can try it ourselves? 

Thanks again
